package: media_manager_autorewrite
version: '1.1.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/media_manager_autorewrite

requires:
    packages:
        media_manager: '^2.0.0'
        yrewrite: '^2.0.0'
    redaxo: '^5.2.0'
    php: '^7'

pages:
    yrewrite/mm_autorewrite:
        title: translate:title
        perm: media_manager_autorewrite[]
